harness:
  secured: false
  service:
    auto: true
    name: neuroglancer
    port: 80
  deployment:
    auto: true
    replicas: 1
    port: 80
    resources:
      limits: {cpu: 4000m, memory: 12Gi}
      requests: {cpu: 10m, memory: 32Mi}
  livenessProbe:
    path: /
  readinessProbe:
    path: /
  tests:
    e2e:
      enabled: false
    unit:
      enabled: false
    api:
      enabled: false
  secured_gatekeepers: false
