harness:
  secured: open
  service:
    auto: true
    name: neuroglancer
    port: 80
  deployment:
    auto: true
    replicas: 1
    port: 80
    resources:
      limits: {cpu: 500m, memory: 512Mi}
      requests: {cpu: 10m, memory: 32Mi}
  livenessProbe:
    path: /
  readinessProbe:
    path: /
  e2e:
    enabled: false
  secured_gatekeepers: false
mainapp: neuroglancer
ingress:
  enabled: true
  letsencrypt: {email: eutychus@metacell.us}
  name: neuroglancer-ingress
  ssl_redirect: true
