replicaCount: 1

image:
  repository: gcr.io/metacellllc/neuroglancer
  pullPolicy: IfNotPresent
  tag: latest

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  letsencrypt:
    email: eutychus@metacell.us
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/issuer: letsencrypt-issuer
  hosts:
    - host: neuroglancer.dev.metacell.us
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls:
   - secretName: dev-neuroglancer-tls
     hosts:
       - neuroglancer.dev.metacell.us

resources:
  limits:
    cpu: 200m
    memory: 528Mi
  requests:
    cpu: 20m
    memory: 64Mi

tls: true
